import type { Metadata } from "next";
import { Nunito, Inconsolata } from "next/font/google";
import "./globals.css";
import { LoadingProvider } from "./ui/components/Loading";
import RecordPlayer from "./ui/components/RecordPlayer";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const inconsolata = Inconsolata({
  variable: "--font-inconsolata",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${inconsolata.variable} antialiased`}
      >
        <LoadingProvider>
          {children}
          <RecordPlayer />
        </LoadingProvider>
      </body>
    </html>
  );
}
